	using UnityEngine;
using System.Collections;

public class Gun : MonoBehaviour
{
	public Rigidbody2D rocket;				// Prefab of the rocket.
	public float speed = 20f;				// The speed the rocket will fire at.


	private PlayerControl playerCtrl;		// Reference to the PlayerControl script.
	private Animator anim;					// Reference to the Animator component.

	bool rotate_sword = false;
	float orginal_z_rotation = 0f;
	bool around = false;

	void Awake()
	{
		// Setting up the references.
		anim = transform.root.gameObject.GetComponent<Animator>();
		playerCtrl = transform.root.GetComponent<PlayerControl>();
	}


	void Update ()
	{

		bool around = false;
		// If the fire button is pressed...
		if(Input.GetButtonDown("Fire1"))
		{
			// ... set the animator Shoot trigger parameter and play the audioclip.
			anim.SetTrigger("Shoot");
			audio.Play();
			rotate_sword = true;
			orginal_z_rotation = this.transform.rotation.z;


		
			// If the player is facing right...
			if(playerCtrl.facingRight)
			{
				// ... instantiate the rocket facing right and set it's velocity to the right. 
				Rigidbody2D bulletInstance = Instantiate(rocket, transform.position, Quaternion.Euler(new Vector3(0,0,0))) as Rigidbody2D;
				bulletInstance.velocity = new Vector2(speed, 0);
			}
			else
			{
				// Otherwise instantiate the rocket facing left and set it's velocity to the left.
				Rigidbody2D bulletInstance = Instantiate(rocket, transform.position, Quaternion.Euler(new Vector3(0,0,180f))) as Rigidbody2D;
				bulletInstance.velocity = new Vector2(-speed, 0);
			} 
		}
		/*if (rotate_sword){
			//this.transform.rotation = new Vector3 (0,0,this.transform.rotation.z + Time.deltaTime * swordspeed);
			this.transform.Rotate(0,0,Time.deltaTime* swordspeed);
		}
		if (this.transform.rotation.z <= 0f){
			around = true;
		}
		if(around && this.transform.rotation.z >= orginal_z_rotation)
		{
			rotate_sword = false;
			around = false;
			this.transform.rotation.z = orginal_z_rotation;

		}*/
	}
}
